# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pre-Merge Actions

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'zulu'
    - name: Grant execute permission for scripts
      run: chmod +x gradlew && chmod +x getMasterThemes.sh
    - name: Pull down the Master Themes
      run: ./getMasterThemes.sh
    - name: Perform quality check
      run: ./gradlew clean check buildPlugin
    - uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.5
      with:
        ide-versions: |
          ideaIC:2020.3.2
          ideaIC:LATEST-EAP-SNAPSHOT
          ideaIU:LATEST-EAP-SNAPSHOT
